default_platform(:android)

platform :android do
  desc "Upload the current release AAB to production."
  lane :deploy do
    upload_to_play_store(
      track: "production",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true,
      release_status: "completed"
    )
  end
end
